FROM apache/airflow:2.10.5

USER root
RUN apt-get update && apt-get install -y vim curl git && rm -rf /var/lib/apt/lists/*
USER airflow

COPY dags /opt/airflow/dags
COPY plugins /opt/airflow/plugins
COPY config /opt/airflow/config